# Generated by Django 4.1.2 on 2022-10-17 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='img',
            new_name='img_url',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='img',
            new_name='img_url',
        ),
    ]
