# Generated by Django 4.1.2 on 2022-10-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0002_rename_img_book_img_url_rename_img_product_img_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_on']},
        ),
    ]
