# Generated by Django 4.1.2 on 2022-10-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0003_alter_book_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Author',
            field=models.CharField(default='', max_length=40),
        ),
    ]
