# Generated by Django 4.1.2 on 2022-10-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0004_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Author',
            field=models.CharField(default='Mike', max_length=40),
        ),
    ]
